#!/usr/bin/env python3
"""
Etsy OAuth2 Authorization Script
Handles the PKCE flow to get access tokens for your Etsy app.
"""

import hashlib
import base64
import secrets
import webbrowser
import requests
from urllib.parse import urlencode, urlparse, parse_qs

# Card Plug Etsy Credentials
CLIENT_ID = "qkshgwscfjv50v21ji3xtaa7"
CLIENT_SECRET = "1760on87u7"
REDIRECT_URI = "https://localhost"  # Etsy allows localhost for personal apps

# Scopes needed for order fulfillment
SCOPES = "transactions_r listings_r shops_r"

def generate_pkce():
    """Generate PKCE code_verifier and code_challenge"""
    # Generate random code_verifier (43-128 chars)
    code_verifier = secrets.token_urlsafe(32)
    
    # Create code_challenge (SHA256 hash, base64url encoded)
    digest = hashlib.sha256(code_verifier.encode()).digest()
    code_challenge = base64.urlsafe_b64encode(digest).rstrip(b'=').decode()
    
    return code_verifier, code_challenge

def get_authorization_url(code_challenge):
    """Build the OAuth authorization URL"""
    params = {
        "response_type": "code",
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "scope": SCOPES,
        "state": secrets.token_urlsafe(16),
        "code_challenge": code_challenge,
        "code_challenge_method": "S256"
    }
    return f"https://www.etsy.com/oauth/connect?{urlencode(params)}"

def exchange_code_for_token(auth_code, code_verifier):
    """Exchange authorization code for access token"""
    url = "https://api.etsy.com/v3/public/oauth/token"
    
    data = {
        "grant_type": "authorization_code",
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "code": auth_code,
        "code_verifier": code_verifier
    }
    
    response = requests.post(url, data=data)
    return response.json()

def main():
    print("=" * 50)
    print("Etsy OAuth2 Authorization - Card Plug")
    print("=" * 50)
    print()
    
    # Step 1: Generate PKCE values
    code_verifier, code_challenge = generate_pkce()
    print(f"Generated PKCE verifier: {code_verifier[:20]}...")
    print()
    
    # Step 2: Build and open authorization URL
    auth_url = get_authorization_url(code_challenge)
    print("Opening browser for authorization...")
    print()
    print("If browser doesn't open, visit this URL:")
    print(auth_url)
    print()
    
    webbrowser.open(auth_url)
    
    # Step 3: Wait for user to authorize and paste redirect URL
    print("-" * 50)
    print("After you click 'Grant Access' on Etsy, you'll be")
    print("redirected to a page that won't load (that's normal).")
    print()
    print("Copy the ENTIRE URL from your browser's address bar")
    print("and paste it here:")
    print("-" * 50)
    print()
    
    redirect_url = input("Paste redirect URL: ").strip()
    
    # Step 4: Extract authorization code from URL
    parsed = urlparse(redirect_url)
    params = parse_qs(parsed.query)
    
    if "code" not in params:
        print("\n❌ Error: No authorization code found in URL")
        print("Make sure you copied the full URL including ?code=...")
        return
    
    auth_code = params["code"][0]
    print(f"\n✓ Got authorization code: {auth_code[:20]}...")
    
    # Step 5: Exchange code for token
    print("\nExchanging code for access token...")
    token_response = exchange_code_for_token(auth_code, code_verifier)
    
    if "access_token" in token_response:
        print("\n" + "=" * 50)
        print("✅ SUCCESS! Here are your credentials:")
        print("=" * 50)
        print(f"Access Token: {token_response['access_token']}")
        print(f"Refresh Token: {token_response['refresh_token']}")
        print(f"Expires In: {token_response.get('expires_in', 'N/A')} seconds")
        print()
        
        # Save to file
        with open("/Users/ellisbot/.openclaw/workspace/credentials/etsy_cardplug.txt", "w") as f:
            f.write(f"# Etsy Card Plug Credentials\n")
            f.write(f"# Generated by etsy_oauth.py\n\n")
            f.write(f"CLIENT_ID={CLIENT_ID}\n")
            f.write(f"CLIENT_SECRET={CLIENT_SECRET}\n")
            f.write(f"ACCESS_TOKEN={token_response['access_token']}\n")
            f.write(f"REFRESH_TOKEN={token_response['refresh_token']}\n")
            f.write(f"SHOP_ID=CardPlugGames\n")
        
        print("✓ Credentials saved to: credentials/etsy_cardplug.txt")
    else:
        print("\n❌ Error getting token:")
        print(token_response)

if __name__ == "__main__":
    main()
